/**
 * Completions, generated statically from the manifest (D2): bash, zsh, fish and
 * PowerShell scripts that never run Node on TAB (D3), plus a Fig spec from the same walk
 * (D5). Every script is deterministic for a manifest, so a snapshot pins it and the shell
 * itself exercises it in CI (D4).
 */
import { type CommandNode, type Manifest, type OptionSpec } from './manifest.js';

export type Shell = 'bash' | 'zsh' | 'fish' | 'pwsh';
export const SHELLS: readonly Shell[] = ['bash', 'zsh', 'fish', 'pwsh'];

/** The options every program serves; offered at every level, `--schema`/`--mcp` at the root. */
const GLOBAL: Record<string, OptionSpec> = {
  json: { type: 'boolean', description: 'machine-readable output' },
  help: { type: 'boolean', description: 'show this help' },
};
const ROOT_ONLY: Record<string, OptionSpec> = {
  schema: { type: 'boolean', description: 'the program as data' },
  mcp: { type: 'boolean', description: 'serve the program as MCP tools' },
};

interface Node {
  /** Typed path, e.g. `['config', 'get']`; empty for the root. */
  path: string[];
  description: string;
  options: Record<string, OptionSpec>;
  children: Node[];
}

function children(manifest: Manifest, at: string[]): Node[] {
  return manifest.commands
    .filter((c) => c.hidden !== true && c.path.length === at.length + 1 && at.every((seg, i) => c.path[i] === seg))
    .map((c) => nodeOf(manifest, c));
}

function nodeOf(manifest: Manifest, c: CommandNode): Node {
  const visible = Object.fromEntries(Object.entries(c.options).filter(([, spec]) => spec.hidden !== true));
  const isRoot = c.path.length === manifest.rootPath.length;
  return {
    path: c.path.slice(manifest.rootPath.length),
    description: c.summary ?? c.description ?? '',
    options: { ...visible, ...GLOBAL, ...(isRoot ? ROOT_ONLY : {}) },
    children: children(manifest, c.path),
  };
}

/** The tree the templates walk; the root's own name is the program name. */
export function completionTree(manifest: Manifest): { program: string; root: Node } {
  const root = manifest.find(manifest.rootPath) ?? { path: manifest.rootPath, options: {} };
  return { program: manifest.rootPath.join('-') || 'program', root: nodeOf(manifest, root) };
}

/** Every node, depth first, root first. */
function walk(root: Node): Node[] {
  const out: Node[] = [];
  const stack = [root];
  while (stack.length > 0) {
    const node = stack.pop();
    if (node !== undefined) {
      out.push(node);
      stack.push(...[...node.children].reverse());
    }
  }
  return out;
}

const sq = (s: string): string => `'${s.replaceAll("'", "'\\''")}'`;
const flags = (name: string, spec: OptionSpec): string[] => (spec.short === undefined ? [`--${name}`] : [`-${spec.short}`, `--${name}`]);
const takesValue = (spec: OptionSpec): boolean => spec.type === 'string';
const fname = (program: string, path: string[]): string => `_${[program, ...path].join('_').replaceAll(/[^A-Za-z0-9_]/g, '_')}`;

// ───── bash ─────────────────────────────────────────────────────────────────────────────

function bashCase(program: string, node: Node): string {
  const opts = Object.entries(node.options).flatMap(([n, s]) => flags(n, s));
  const subs = node.children.map((c) => c.path[c.path.length - 1] ?? '');
  const valued = Object.entries(node.options)
    .filter(([, s]) => takesValue(s))
    .map(([n, s]) => `      ${flags(n, s).join('|')}) COMPREPLY=($(compgen -W ${sq((s.choices ?? []).join(' '))} -- "$cur")); return ;;`)
    .join('\n');
  return `  ${fname(program, node.path)}() {
    case "$prev" in
${valued === '' ? '      *) ;;' : `${valued}\n      *) ;;`}
    esac
    if [[ "$cur" == -* ]]; then COMPREPLY=($(compgen -W ${sq(opts.join(' '))} -- "$cur")); return; fi
    COMPREPLY=($(compgen -W ${sq(subs.join(' '))} -- "$cur"))
  }`;
}

function bash(program: string, root: Node): string {
  const nodes = walk(root);
  const dispatch = nodes
    .filter((n) => n.path.length > 0)
    .map((n) => `      ${sq(n.path.join(' '))}) ${fname(program, n.path)}; return ;;`)
    .join('\n');
  return `# ${program} completion for bash, generated by burgee — never runs ${program} on TAB.
# Install: ${program} completion bash > ~/.local/share/bash-completion/completions/${program}
_${program}_main() {
  local cur prev words cword
  _get_comp_words_by_ref -n : cur prev words cword 2>/dev/null || { cur="\${COMP_WORDS[COMP_CWORD]}"; prev="\${COMP_WORDS[COMP_CWORD-1]}"; words=("\${COMP_WORDS[@]}"); cword=$COMP_CWORD; }
${nodes.map((n) => bashCase(program, n)).join('\n')}
  # The deepest command named by the words before the cursor decides what to offer.
  local path="" i
  for ((i = 1; i < cword; i++)); do
    case "\${words[i]}" in -*) continue ;; esac
    case "\${path:+$path }\${words[i]}" in
${nodes
  .filter((n) => n.path.length > 0)
  .map((n) => `      ${sq(n.path.join(' '))}) path="\${path:+$path }\${words[i]}" ;;`)
  .join('\n')}
    esac
  done
  case "$path" in
${dispatch}
      *) ${fname(program, [])} ;;
  esac
}
complete -F _${program}_main ${program}
`;
}

// ───── zsh ──────────────────────────────────────────────────────────────────────────────

function zshOptionSpec(name: string, spec: OptionSpec): string {
  const desc = (spec.description ?? '').replaceAll(/[[\]:]/g, ' ');
  const action = spec.choices === undefined ? ' ' : `(${spec.choices.join(' ')})`;
  const value = takesValue(spec) ? `:${name}:${action}` : '';
  return flags(name, spec)
    .map((f) => sq(`${f}[${desc}]${value}`))
    .join(' ');
}

function zshFunction(program: string, node: Node): string {
  const options = Object.entries(node.options).map(([n, s]) => zshOptionSpec(n, s));
  if (node.children.length === 0) {
    return `${fname(program, node.path)}() {\n  _arguments -s ${options.join(' ')} '*: :_files'\n}`;
  }
  const subs = node.children.map((c) => sq(`${c.path[c.path.length - 1] ?? ''}[${c.description.replaceAll(/[[\]:]/g, ' ')}]`)).join(' ');
  const dispatch = node.children.map((c) => `      ${c.path[c.path.length - 1] ?? ''}) ${fname(program, c.path)} ;;`).join('\n');
  return `${fname(program, node.path)}() {
  local context state state_descr line
  typeset -A opt_args
  _arguments -s -C ${options.join(' ')} '1: :->command' '*:: :->args'
  case $state in
    command) _values 'command' ${subs} ;;
    args) case $line[1] in
${dispatch}
    esac ;;
  esac
}`;
}

function zsh(program: string, root: Node): string {
  return `#compdef ${program}
# ${program} completion for zsh, generated by burgee — never runs ${program} on TAB.
# Install: ${program} completion zsh > "\${fpath[1]}/_${program}" && compinit
${walk(root).map((n) => zshFunction(program, n)).join('\n')}
if [[ $zsh_eval_context[-1] == loadautofunc ]]; then ${fname(program, [])} "$@"; else compdef ${fname(program, [])} ${program}; fi
`;
}

// ───── fish ─────────────────────────────────────────────────────────────────────────────

function fishCondition(node: Node): string {
  if (node.path.length === 0) return '__fish_use_subcommand';
  return node.path.map((seg) => `__fish_seen_subcommand_from ${seg}`).join('; and ');
}

function fishOption(program: string, cond: string, name: string, spec: OptionSpec): string {
  const short = spec.short === undefined ? '' : ` -s ${spec.short}`;
  const choices = spec.choices === undefined ? '' : ` -f -a ${sq(spec.choices.join(' '))}`;
  const value = takesValue(spec) ? ` -r${choices}` : '';
  return `complete -c ${program} -n ${cond}${short} -l ${name}${value} -d ${sq(spec.description ?? '')}`;
}

function fish(program: string, root: Node): string {
  const lines: string[] = [];
  for (const node of walk(root)) {
    const cond = sq(fishCondition(node));
    for (const c of node.children) lines.push(`complete -c ${program} -n ${cond} -f -a ${c.path[c.path.length - 1] ?? ''} -d ${sq(c.description)}`);
    for (const [name, spec] of Object.entries(node.options)) lines.push(fishOption(program, cond, name, spec));
  }
  return `# ${program} completion for fish, generated by burgee — never runs ${program} on TAB.
# Install: ${program} completion fish > ~/.config/fish/completions/${program}.fish
${lines.join('\n')}
`;
}

// ───── PowerShell ───────────────────────────────────────────────────────────────────────

function pwshEntry(node: Node): string {
  const subs = node.children.map((c) => `@('${c.path[c.path.length - 1] ?? ''}', 'Command', '${c.description.replaceAll("'", "''")}')`);
  const opts = Object.entries(node.options).flatMap(([n, s]) =>
    flags(n, s).map((f) => `@('${f}', 'ParameterName', '${(s.description ?? '').replaceAll("'", "''")}')`),
  );
  const values = Object.entries(node.options)
    .filter(([, s]) => s.choices !== undefined)
    .map(([n, s]) => `'--${n}' = @(${(s.choices ?? []).map((c) => `'${c}'`).join(', ')})`);
  return `    '${node.path.join(' ')}' = @{ Items = @(${[...subs, ...opts].join(', ')}); Values = @{ ${values.join('; ')} } }`;
}

function pwsh(program: string, root: Node): string {
  return `# ${program} completion for PowerShell, generated by burgee — never runs ${program} on TAB.
# Install: ${program} completion pwsh > ${program}-completion.ps1, then dot-source it from $PROFILE
Register-ArgumentCompleter -Native -CommandName '${program}' -ScriptBlock {
  param($wordToComplete, $commandAst, $cursorPosition)
  $table = @{
${walk(root).map(pwshEntry).join('\n')}
  }
  $words = @($commandAst.CommandElements | ForEach-Object { $_.Extent.Text } | Select-Object -Skip 1)
  if ($wordToComplete -ne '' -and $words.Count -gt 0) { $words = $words[0..($words.Count - 2)] }
  $path = ''
  foreach ($w in $words) {
    if ($w -like '-*') { continue }
    $candidate = if ($path -eq '') { $w } else { "$path $w" }
    if ($table.ContainsKey($candidate)) { $path = $candidate }
  }
  $entry = $table[$path]
  $prev = if ($words.Count -gt 0) { $words[$words.Count - 1] } else { '' }
  if ($entry.Values.ContainsKey($prev)) {
    $entry.Values[$prev] | Where-Object { $_ -like "$wordToComplete*" } | ForEach-Object { [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_) }
    return
  }
  $entry.Items | Where-Object { $_[0] -like "$wordToComplete*" } | ForEach-Object { [System.Management.Automation.CompletionResult]::new($_[0], $_[0], $_[1], $(if ($_[2] -eq '') { $_[0] } else { $_[2] })) }
}
`;
}

// ───── Fig ──────────────────────────────────────────────────────────────────────────────

interface FigOption {
  name: string[];
  description?: string;
  args?: { name: string; suggestions?: string[] };
}
interface FigSubcommand {
  name: string;
  description?: string;
  subcommands?: FigSubcommand[];
  options?: FigOption[];
}

function figOptions(node: Node): FigOption[] {
  return Object.entries(node.options).map(([n, s]) => {
    const o: FigOption = { name: flags(n, s) };
    if (s.description !== undefined) o.description = s.description;
    if (takesValue(s)) o.args = { name: s.placeholder ?? 'value', ...(s.choices === undefined ? {} : { suggestions: s.choices }) };
    return o;
  });
}

/** A Fig spec (`Fig.Spec`) from the same walk (D5): one entry per node, children attached by path. */
export function renderFigSpec(manifest: Manifest): FigSubcommand {
  const { program, root } = completionTree(manifest);
  const entries = new Map<string, FigSubcommand>();
  for (const node of walk(root)) {
    const entry: FigSubcommand = { name: node.path[node.path.length - 1] ?? program, options: figOptions(node) };
    if (node.description !== '') entry.description = node.description;
    entries.set(node.path.join(' '), entry);
    if (node.path.length === 0) continue;
    const parent = entries.get(node.path.slice(0, -1).join(' '));
    if (parent !== undefined) (parent.subcommands ??= []).push(entry);
  }
  return entries.get('') ?? { name: program, options: [] };
}

export function renderCompletion(manifest: Manifest, shell: Shell): string {
  const { program, root } = completionTree(manifest);
  switch (shell) {
    case 'bash':
      return bash(program, root);
    case 'zsh':
      return zsh(program, root);
    case 'fish':
      return fish(program, root);
    case 'pwsh':
      return pwsh(program, root);
  }
}
