/**
 * Writes apps/docs/content/docs/benchmarks.mdx from the last `npm run bench`. Generated,
 * never hand-edited, so every published number is the measured number (B7) — and so the
 * ones that are *not* measured say so on the page rather than in a commit message.
 */
import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(fileURLToPath(new URL('..', import.meta.url)));
const RESULTS = join(root, 'benchmarks', 'results');
const OUT = join(root, 'apps', 'docs', 'content', 'docs', 'benchmarks.mdx');
const ISO_DATE = 10;
const SHORT_SHA = 7;
/** Ratios to three decimals: enough to see a regression, few enough to read. */
const RATIO_PLACES = 3;
const MS_PLACES = 1;
const PERCENT = 100;

interface Record_ {
  axis: string;
  variant: string;
  metric: string;
  unit: string;
  samples: number;
  median: number;
  p95: number;
  note?: string;
  gate?: { max?: number; min?: number; why: string };
}
interface Claim {
  claim: string;
  source: string;
  target: string;
  measured?: number;
  unit?: string;
  met?: boolean;
  reason?: string;
}
interface Machine {
  os: string;
  arch: string;
  cpu: string;
  cores: number;
  node: string;
  ci: boolean;
}
interface Doc {
  suite: string;
  measured: string;
  commit: string;
  machine: Machine;
  axes: Record<string, { status: string; reason?: string; method?: string }>;
  records: Record_[];
  claims: Record<string, Claim>;
}

/** The newest dated file of a suite, or nothing if the suite has never run here. */
function latest(suite: string): Doc | undefined {
  const dir = join(RESULTS, suite);
  if (!existsSync(dir)) return undefined;
  const files = readdirSync(dir)
    .filter((f) => f.endsWith('.json'))
    .toSorted();
  const last = files.at(-1);
  return last === undefined ? undefined : (JSON.parse(readFileSync(join(dir, last), 'utf8')) as Doc);
}

const cheap = latest('cli-benchmarks');
const agent = latest('agent-cli-bench');
if (cheap === undefined) throw new Error('no results under benchmarks/results/cli-benchmarks — run `npm run bench` first');

const pick = (doc: Doc, metric: string): Record_[] => doc.records.filter((r) => r.metric === metric);
const num = (n: number): string => n.toLocaleString('en-US');

const coldStart = pick(cheap, 'cold-start-ms').map((r) => `| \`${r.variant}\` | ${r.median.toFixed(MS_PLACES)} | ${r.p95.toFixed(MS_PLACES)} | ${String(r.samples)} |`);
const ratios = pick(cheap, 'cold-start-ratio').map((r) => `| ${r.variant} | **${r.median.toFixed(RATIO_PLACES)}×** | ${r.p95.toFixed(RATIO_PLACES)}× | ${r.gate === undefined ? '—' : `≤ ${String(r.gate.max)}`} |`);

const compatRows = pick(cheap, 'pass-rate').map((r) => {
  const passing = pick(cheap, 'passing-tests').find((p) => p.variant === r.variant);
  return `| **${r.variant}** | ${num(passing?.median ?? 0)} | ${(r.median * PERCENT).toFixed(1)}% |`;
});

const bundled = pick(cheap, 'bundled-bytes');
const installed = pick(cheap, 'installed-bytes');
const weightRows = pick(cheap, 'bundled-bytes-ratio').map((r) => {
  const [ours, theirs] = r.variant.split(' ÷ ') as [string, string];
  const b = (v: string): string => num(bundled.find((x) => x.variant === v)?.median ?? 0);
  const i = (v: string): string => num(installed.find((x) => x.variant === v)?.median ?? 0);
  return `| \`${ours}\` | \`${theirs}\` | ${b(ours)} | ${b(theirs)} | **${r.median.toFixed(RATIO_PLACES)}×** | ${i(ours)} | ${i(theirs)} |`;
});

function claimVerdict(c: Claim): string {
  if (c.met === undefined) return `**unmeasured** — ${c.reason ?? ''}`;
  return c.met ? '✅ met' : '❌ **not met**';
}

const claimRow = (id: string, c: Claim): string => {
  const verdict = claimVerdict(c);
  const measured = c.measured === undefined ? '—' : `${num(c.measured)} ${c.unit ?? ''}`;
  // The target is rendered as code: MDX reads a bare `<=` as the start of a JSX tag.
  return `| ${c.claim} | \`${c.target}\` | ${measured} | ${verdict} |`;
};
const claims = [...Object.entries(cheap.claims), ...Object.entries(agent?.claims ?? {})].map(([id, c]) => claimRow(id, c));

const m = cheap.machine;
const agentAxis = agent?.axes['agent'];
const agentLine =
  agentAxis === undefined || agentAxis.status === 'measured'
    ? ''
    : `\n> **B1 has not run.** The agent-cost axis reports **${agentAxis.status}**: ${agentAxis.reason ?? ''}.\n> Its two rows below read *unmeasured*, and they will keep reading *unmeasured* until it runs.\n> They are not estimates, and there are no estimates on this page.\n`;

writeFileSync(
  OUT,
  `---
title: Benchmarks
description: Every number this project claims in public, measured — and the ones that are not measured, saying so.
---

Generated by \`npm run bench:page\` from the run of ${cheap.measured.slice(0, ISO_DATE)} at commit \`${cheap.commit.slice(0, SHORT_SHA)}\`.
Do not edit by hand.
${agentLine}
## Published claims, settled

Every number this repository states in public, checked against the record that settles it.
**"Not met" and "unmeasured" are different outcomes** and never collapse into each other:
one says we measured and it is not true, the other says we have not measured.

| Claim | Target | Measured | |
| :--- | :--- | ---: | :--- |
${claims.join('\n')}

## B2 — cold start

Spawned processes, not an in-process micro-benchmark: process time is what a user and an
agent actually pay, and excluding Node's own startup would flatter every row.
**\`bare node\` is the floor row** and most of every other number.

> These milliseconds are a property of the machine that ran them —
> ${m.cpu}, ${String(m.cores)} cores, ${m.os}/${m.arch}, Node ${m.node}${m.ci ? ', on CI' : ''} — and are **not comparable across
> machines**. Nothing gates on them. What is gated and banded is the ratio below, taken
> between two spawns interleaved in the same run, which cancels the machine out.

| Variant | p50 ms | p95 ms | spawns |
| :--- | ---: | ---: | ---: |
${coldStart.join('\n')}

| Ratio | p50 | p95 | gate |
| :--- | ---: | ---: | ---: |
${ratios.join('\n')}

## B3 — compatibility

Read from \`compat-oracle\` and never recomputed here: two implementations of a
compatibility rate produce two rates. The full method, and the control column that proves
the gate works, are on [Compatibility](/docs/compatibility).

| Host | Passing | Rate |
| :--- | ---: | ---: |
${compatRows.join('\n')}

## B4 — weight

**Bundled** is what your application grows by when you import that entry point: a fixture
importing exactly it, one symbol used, esbuild-minified — the incumbent measured by the
same command over the same fixture shape. A tarball size answers a different question.

**Installed** is what \`npm install\` puts on disk, including everything the package drags
in. Ours drag nothing, which is where the two columns diverge most; but one of our packages
serves every entry point it publishes, so the installed column is not per-entry-point and
nothing gates on it.

| Entry point | Replaces | Bundled | Theirs | Ratio | Installed | Theirs |
| :--- | :--- | ---: | ---: | ---: | ---: | ---: |
${weightRows.join('\n')}

## Reproduce

\`\`\`bash
npm install
npx turbo run build
npm run bench -- --check
\`\`\`

Results are written to \`benchmarks/results/<suite>/<date>.json\` and read by the Stage 6
control bands in \`.sdlc/bands/control-bands.json\`. The suite refuses to emit a band value
it did not measure; see \`benchmarks/README.md\`.
`,
);
process.stdout.write(`wrote ${OUT}\n`);
