/**
 * burgee's own brand, declared once and projected into every identity surface.
 *
 * `npm run brand` writes them; `npm run brand -- --check` fails if what is on
 * disk has drifted from what the declaration produces. The check is the point:
 * before this existed the mark was hand-copied into three files with a comment
 * as the only thing holding them together.
 *
 * This is also the package's first adopter. If `burgee/brand` is awkward to use
 * here, it will be awkward for everyone.
 */
import { readFileSync, mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

import {
  burgeeFlagPath,
  chargeRotation,
  chargeTransform,
  defineBurgee,
  type BurgeeBrand,
} from 'burgee/brand';

const repo = fileURLToPath(new URL('..', import.meta.url));

/**
 * The declaration. Every colour is a documented Interlace token from
 * brand-assets/: the deep pair for both the charge and the field's two ends,
 * and the near-black already used across the profile assets.
 */
const ROCK = '#a84c17';
const JUNIPER = '#0a6b47';
const INK = '#0a0a0a';

const BURGEE_DECLARATION: BurgeeBrand = {
  name: 'burgee',
  // The charge, in the deep pair.
  mark: { lead: ROCK, follow: JUNIPER },
  // The field, run backwards: juniper where the rock bar sits, rock where the
  // juniper bar sits. The ink stop in the middle is what makes the deep pair
  // legible on its own field — see the contrast test in brand.test.ts.
  field: [
    { offset: 0, color: JUNIPER },
    { offset: 0.5, color: INK },
    { offset: 1, color: ROCK },
  ],
};

const burgee = defineBurgee(BURGEE_DECLARATION);

/** Master size for the standalone flag file; rasterisers downsample from here. */
const MASTER = 512;

const TAGLINE =
  "Everything a CLI needs that isn't your CLI. Written once, served to humans and agents alike.";

const GENERATED = '<!-- Generated by scripts/brand.ts. Run `npm run brand`. Do not edit. -->';

/** Every surface, and the file that consumes it. */
const surfaces: ReadonlyArray<{ path: string; svg: string }> = [
  { path: 'brand-assets/burgee-flag.svg', svg: burgee.flag(MASTER) },
  { path: 'brand-assets/burgee-lockup.svg', svg: burgee.lockup({ theme: 'dark' }) },
  { path: 'brand-assets/burgee-lockup-light.svg', svg: burgee.lockup({ theme: 'light' }) },
  { path: 'brand-assets/burgee-og.svg', svg: burgee.og({ subtitle: TAGLINE }) },
  { path: 'brand-assets/burgee-cover.svg', svg: burgee.cover({ subtitle: TAGLINE }) },
  // The favicon master the docs site serves at /icon.svg.
  { path: 'apps/docs/src/app/icon.svg', svg: burgee.favicon() },
];

const MARK_COMPONENT = 'apps/docs/src/components/burgee-flag.tsx';

/**
 * The values the React component must carry. It writes them as JSX rather than
 * as one generated string, so the check is per value: colours, the swallowtail
 * path, the charge placement and the angle.
 */
const FLAG_DATA_URI = `data:image/svg+xml;base64,${Buffer.from(burgee.flag(MASTER)).toString('base64')}`;

const COMPONENT_VALUES: ReadonlyArray<[string, string]> = [
  ['rock', ROCK],
  ['juniper', JUNIPER],
  ['ink', INK],
  ['flag path', burgeeFlagPath()],
  ['charge placement', chargeTransform()],
  ['charge angle', chargeRotation()],
  ['data URI', FLAG_DATA_URI],
];

function body(svg: string): string {
  return `${GENERATED}\n${svg}\n`;
}

function read(path: string): string | null {
  try {
    return readFileSync(join(repo, path), 'utf8');
  } catch {
    return null;
  }
}

/**
 * The component keeps its paths as literals so it stays a plain React component
 * with no build-time dependency on this script. That is a copy, so it is checked.
 */
function componentDrift(): string | null {
  const source = read(MARK_COMPONENT);
  if (source === null) return `${MARK_COMPONENT} is missing`;
  for (const [what, value] of COMPONENT_VALUES) {
    if (!source.includes(value)) return `${MARK_COMPONENT}: ${what} is not '${value}'`;
  }
  return null;
}

const check = process.argv.includes('--check');
const drifted: string[] = [];

for (const surface of surfaces) {
  const want = body(surface.svg);
  if (check) {
    if (read(surface.path) !== want) drifted.push(surface.path);
    continue;
  }
  const target = join(repo, surface.path);
  mkdirSync(dirname(target), { recursive: true });
  writeFileSync(target, want);
}

const componentProblem = componentDrift();
if (componentProblem !== null) drifted.push(componentProblem);

if (check && drifted.length > 0) {
  console.error('brand assets have drifted from the declaration:');
  for (const d of drifted) console.error(`  ${d}`);
  console.error('\nrun `npm run brand` to regenerate.');
  process.exitCode = 1;
} else if (check) {
  console.log(`brand: ${surfaces.length} surfaces and the mark component match the declaration`);
} else {
  for (const surface of surfaces) console.log(`wrote ${relative('.', surface.path)}`);
  // satori cannot resolve `url(#gradient)`, so the OG route draws the flag as an
  // image rather than as SVG elements. Print the value it must carry.
  console.log(`\nBURGEE_FLAG_DATA_URI (paste into burgee-flag.tsx):\n${FLAG_DATA_URI}`);
}

// Writing cannot fix the component: it keeps its own literals, so a mismatch
// after a write is a hand edit someone still owes.
if (!check && componentProblem !== null) {
  console.error(`\n${componentProblem}`);
  console.error('the component carries its own copy — update it by hand, then re-run --check.');
  process.exitCode = 1;
}

