/**
 * burgee's own brand, declared once and projected into every identity surface.
 *
 * `npm run brand` writes them; `npm run brand -- --check` fails if what is on
 * disk has drifted from what the declaration produces. The check is the point:
 * before this existed the mark was hand-copied into three files with a comment
 * as the only thing holding them together.
 *
 * This is also the package's first adopter. If `burgee/brand` is awkward to use
 * here, it will be awkward for everyone.
 */
import { readFileSync, mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

import {
  BURGEE_FLAG,
  burgeeFlagPath,
  placeCharge,
  CHARGE,
  chargeGroup,
  chargeRotation,
  chargeTransform,
  defineBurgee,
  type BurgeeBrand,
} from 'burgee/brand';

const repo = fileURLToPath(new URL('..', import.meta.url));

/**
 * The declaration. Every colour is a documented Interlace token: the near-black
 * the whole line is cut from, and the LIFTED pair — rock and juniper as
 * `roundel/theme` declares them — for the charge. The deep pair (#a84c17,
 * #0a6b47) is still the terminal palette; it is not used here, because on ink it
 * clears the 3:1 floor by 3.50:1 and 3.02:1 where the lifted pair clears it by
 * 7.24:1 and 5.11:1, and a logo has no stylesheet to compensate with.
 */
const INK = '#0a0a0a';
const MARK_CENTRE = 50;
/** Where burgee's own flag has its hoist, so a shifted copy can be measured from it. */
const HOIST_X = 10;
/** And where its top edge starts, so a hoisted copy hangs from the truck. */
const FLAG_TOP = 20;
/** The light ground the cards already use, borrowed as an outline colour. */
const PAPER = '#efe9dd';
const ROCK_LIFT = '#f4794a';
const JUNIPER_LIFT = '#0d9460';

/**
 * The light. One number, shared by every mark in the line: a highlight this
 * bright laid across the field, which is what turns a flat gradient into
 * something with a front. Low on purpose — the charge's measured contrast is
 * the floor, and a sheen bright enough to be noticed on its own would eat it.
 */
const SHEEN = 0.16;

/** And the edge that light catches. The only depth a logo gets to keep. */
const BEVEL = 0.28;

/**
 * A flat ink body needs an outline or it dissolves into a dark card — the price
 * of dropping the gradient. One band in the light ground's own colour: on paper
 * it disappears into the page and the body carries the silhouette; on ink it is
 * the thing separating the two.
 */
const OUTLINE = [{ color: PAPER, width: 2 }];

const BURGEE_DECLARATION: BurgeeBrand = {
  name: 'burgee',
  sheen: SHEEN,
  bevel: BEVEL,
  // The charge, in the LIFTED pair. The deep pair was chosen for a field that
  // fell through ink at its midpoint; on a flat ink field the lifted pair clears
  // it at 7.24:1 and 5.11:1 where the deep one only just made 3.50 and 3.02.
  mark: { lead: ROCK_LIFT, follow: JUNIPER_LIFT },
  // Flat, not a gradient. The gradient was designed for a thin flag, where its
  // ink midpoint sat exactly under the charge and did contrast work; stretched
  // across a ring or a bird it turned the middle of every mark to mud. Flat ink
  // keeps the contrast the midpoint was there for and loses the smear.
  field: [{ offset: 0, color: INK }],
  bordure: OUTLINE,
};

const burgee = defineBurgee(BURGEE_DECLARATION);

/** Master size for the standalone flag file; rasterisers downsample from here. */
const MASTER = 512;

const TAGLINE =
  "Everything a CLI needs that isn't your CLI. Written once, served to humans and agents alike.";

const GENERATED = '<!-- Generated by scripts/brand.ts. Run `npm run brand`. Do not edit. -->';

/**
 * The siblings. Same field, same colours, same projections — and each in the
 * shape of the thing it is named after, because a roundel that flies as a flag
 * is just burgee's flag with rings on it. Only burgee flies the swallowtail.
 *
 * What holds the family together instead is the field, unchanged from the flag:
 * juniper through ink to rock along the same axis. Its ink midpoint lands where
 * the charge lands, which is why the Interlace mark reads on all four.
 *
 * Every shape is one path in the same `0 0 100 100` box, filled `evenodd` — a
 * nested subpath cuts a hole, which is how the roundel gets its centre and the
 * parrot gets an eye. Overlapping subpaths would cut holes too, so the shapes
 * are drawn as single closed outlines.
 */
const FAMILY_FIELD = [{ offset: 0, color: INK }];
const LIFTED = { lead: ROCK_LIFT, follow: JUNIPER_LIFT } as const;

/** Every sibling is lit the same way, from the same declaration. */
const LIT = { field: FAMILY_FIELD, mark: LIFTED, sheen: SHEEN, bevel: BEVEL, bordure: OUTLINE } as const;

/**
 * How big the Interlace mark is in each sibling, as a share of the size it is on
 * burgee's own flag. Not one number: the mark sits in a ring's centre, on a flag
 * and on a bird's body, and each has a different amount of room.
 */
const MARK_SHARE = {
  roundel: 1.15,
  flagstaff: 0.66,
  caique: 0.78,
  linegauge: 0.62,
  seniority: 0.68,
  bellpull: 0.8,
  closeout: 0.9,
} as const;

/**
 * The Interlace mark, in the lifted pair, at a share of its usual size.
 *
 * `chargeGroup` places the bars at the charge point of the box it is drawn in,
 * and this markup is itself placed at the charge point — so without the nudge
 * back to the box's centre the mark would land off-centre twice over.
 */
const RECENTRE = MARK_CENTRE - CHARGE.x;
const interlace = (
  scale: number,
  at: { x: number; y: number } = CHARGE,
  colors: { lead: string; follow: string } = LIFTED,
): string => {
  const dx = RECENTRE + (at.x - CHARGE.x) / CHARGE.scale;
  const dy = (at.y - CHARGE.y) / CHARGE.scale;
  return `<g transform="translate(${dx.toFixed(2)} ${dy.toFixed(2)})">${chargeGroup(colors, scale)}</g>`;
};

/**
 * A roundel, as the insignia actually works: concentric rings, and one charge in
 * the middle. Every air force on the reference sheet is the same grammar — an
 * outer field, a ring inside it, and something at the centre that says whose it
 * is. Ours is a solid ink field, a rock ring, and the Interlace mark.
 *
 * Centred on the charge point rather than the box, so rings and mark share a
 * centre.
 */
const RING = { disc: 44, band: 36, inner: 29 } as const;
const circle = (r: number): string =>
  `M${CHARGE.x - r} ${CHARGE.y} a${r} ${r} 0 1 1 ${r * 2} 0 a${r} ${r} 0 1 1 ${-r * 2} 0 Z`;

const ROUNDEL = circle(RING.disc);
const ROUNDEL_RINGS =
  `<path d="${circle(RING.band)}" fill="${ROCK_LIFT}"/>` +
  `<path d="${circle(RING.inner)}" fill="${INK}"/>`;

/**
 * A flagstaff: a staff, and the flag flying from it.
 *
 * The signpost at Flagstaff was the reference, and a signpost is what it drew —
 * a board, a stripe, a post, three things where burgee gets away with one. The
 * package is the staff a flag is hoisted on, so the mark is a staff with a flag
 * on it and nothing else. The flag is burgee's own points, scaled and shifted
 * clear of the staff: a translation of the exported geometry, never a copy.
 */
const STAFF = { x: 14, width: 11, top: 4, bottom: 96 } as const;
const HOISTED = { scale: 0.66, top: 10 } as const;
const hoist = STAFF.x + STAFF.width;

const flown = ([x, y]: readonly [number, number]): string =>
  `${(hoist + (x - HOIST_X) * HOISTED.scale).toFixed(2)} ` +
  `${(HOISTED.top + (y - FLAG_TOP) * HOISTED.scale).toFixed(2)}`;

const STAFF_AND_FLAG = [
  `M${STAFF.x} ${STAFF.top + STAFF.width / 2}` +
    ` a${STAFF.width / 2} ${STAFF.width / 2} 0 0 1 ${STAFF.width} 0` +
    ` V${STAFF.bottom} H${STAFF.x} Z`,
  `M${BURGEE_FLAG.map(flown).join(' L')} Z`,
].join(' ');

/** The flown flag's centre, where its charge goes — as on burgee's own flag. */
const SIGN_CENTRE = {
  x: hoist + (CHARGE.x - HOIST_X) * HOISTED.scale,
  y: HOISTED.top + (CHARGE.y - FLAG_TOP) * HOISTED.scale,
} as const;

/**
 * A caique, in its own colours: black cap over an orange throat, a white belly,
 * and a green wing — the black-headed caique, which is the bird the package is
 * named after and, by luck rather than design, already the Interlace palette.
 *
 * The body is the silhouette; the cap is simply the body showing through. Every
 * other patch is a marking, clipped to the body, so a patch can be drawn
 * generously and let the outline decide where it ends.
 */
const PARROT = [
  // Crown and nape, over the back and out along the tail.
  'M26 27',
  'C26 14, 37 4, 50 8',
  'C63 12, 72 24, 71 38',
  'C71 50, 78 58, 88 68',
  'C94 74, 97 86, 93 95',
  'C83 91, 71 83, 63 73',
  // Underside, and back up the breast to the chin.
  'C57 83, 45 89, 34 85',
  'C23 80, 17 67, 20 52',
  'C21 47, 23 44, 26 42',
  // The beak: small, and hooked below the mouth. Long and level it reads as a
  // bill; as tall as the head it reads as a second lobe of the same blob.
  'C21 44, 17 46, 15 49',
  'C12 41, 15 31, 26 27 Z',
  // The eye, cut through rather than painted on.
  'M39 21 a4.6 4.6 0 1 1 9.2 0 a4.6 4.6 0 1 1 -9.2 0 Z',
].join(' ');

/** The wing's centre, where the mark rides. */
const WING = { x: 52, y: 52 } as const;

/**
 * A line gauge: the printer's steel rule, marked in picas and points.
 *
 * The ticks are cut THROUGH the rule rather than drawn on it — a counter under
 * `evenodd` — so they are the one thing on the mark that is not ink, which is
 * what a rule's markings are: absence, machined into steel.
 */
const RULE = { left: 2, right: 98, top: 30, bottom: 70 } as const;
const TICK = { width: 1.8, step: 5.5, long: 14, short: 8, from: 8 } as const;

const ticks = (): string => {
  const out: string[] = [];
  for (let x = TICK.from, i = 0; x <= RULE.right - TICK.from; x += TICK.step, i++) {
    const depth = i % 2 === 0 ? TICK.long : TICK.short;
    out.push(
      `M${x} ${RULE.top} h${TICK.width} v${depth} h${-TICK.width} Z`,
    );
  }
  return out.join(' ');
};

const LINEGAUGE = `M${RULE.left} ${RULE.top} H${RULE.right} V${RULE.bottom} H${RULE.left} Z ${ticks()}`;
/** Below the ticks, on the rule's plain half. */
const RULE_FACE = { x: 50, y: 58 } as const;

/**
 * Seniority: rank chevrons. Longer service, higher position, and therefore the
 * one that wins when two sources want the same value. Three of them, because
 * one is a mark and two is a coincidence.
 */
const CHEVRON = { left: 12, right: 88, rise: 18, thickness: 10, bases: [52, 70, 88] } as const;

const chevrons = (): string =>
  CHEVRON.bases.map((y) =>
    [
      `M${CHEVRON.left} ${y}`,
      `L50 ${y - CHEVRON.rise}`,
      `L${CHEVRON.right} ${y}`,
      `V${y + CHEVRON.thickness}`,
      `L50 ${y - CHEVRON.rise + CHEVRON.thickness}`,
      `L${CHEVRON.left} ${y + CHEVRON.thickness}`,
      'Z',
    ].join(' '),
  ).join(' ');

const SENIORITY = chevrons();
/** Above the stripes, where a rank badge carries its device. */
const RANK = { x: 50, y: 20 } as const;

/**
 * A bellpull: the cord in one room, wired to a bell in another. Cord and pull
 * are one outline — a cord ending inside its own handle would cut a hole where
 * the two overlap.
 */
const CORD = { left: 46, right: 54, top: 6, waist: 56, pull: 22 } as const;
const BELLPULL =
  `M${CORD.left} ${CORD.top} a4 4 0 0 1 8 0 V${CORD.waist}` +
  ` A${CORD.pull} ${CORD.pull} 0 1 1 ${CORD.left} ${CORD.waist} Z`;
/** On the pull, which is the part a hand actually takes. */
const PULL = { x: 50, y: 74 } as const;

/**
 * Closeout: the double rule an accountant draws under a settled total. Two
 * lines mean the column is finished and nothing below it is still open.
 */
const RULED = { left: 12, right: 88, thickness: 9, at: [66, 84] } as const;
const CLOSEOUT = RULED.at
  .map((y) => `M${RULED.left} ${y} H${RULED.right} V${y + RULED.thickness} H${RULED.left} Z`)
  .join(' ');
/** Above the rule: the total it is drawn under. */
const TOTAL = { x: 50, y: 38 } as const;

const siblings: ReadonlyArray<{ name: string; tagline: string; brand: BurgeeBrand }> = [
  {
    name: 'roundel',
    tagline: 'The colours a CLI carries.',
    brand: {
      ...LIT,
      name: 'roundel',
      shape: ROUNDEL,
      markings: ROUNDEL_RINGS,
      charge: interlace(MARK_SHARE.roundel),
    },
  },
  {
    name: 'flagstaff',
    tagline: 'The staff the flag flies from.',
    brand: {
      ...LIT,
      name: 'flagstaff',
      shape: STAFF_AND_FLAG,
      charge: interlace(MARK_SHARE.flagstaff, SIGN_CENTRE),
    },
  },
  {
    name: 'caique',
    tagline: 'Prompts that never hang.',
    brand: {
      ...LIT,
      name: 'caique',
      shape: PARROT,
      charge: interlace(MARK_SHARE.caique, WING),
    },
  },
  {
    name: 'linegauge',
    tagline: "The printer's rule, for text.",
    brand: {
      ...LIT,
      name: 'linegauge',
      shape: LINEGAUGE,
      charge: interlace(MARK_SHARE.linegauge, RULE_FACE),
    },
  },
  {
    name: 'seniority',
    tagline: 'Which source outranks which.',
    brand: {
      ...LIT,
      name: 'seniority',
      shape: SENIORITY,
      charge: interlace(MARK_SHARE.seniority, RANK),
    },
  },
  {
    name: 'bellpull',
    tagline: 'Pull here, work happens there.',
    brand: {
      ...LIT,
      name: 'bellpull',
      shape: BELLPULL,
      charge: interlace(MARK_SHARE.bellpull, PULL),
    },
  },
  {
    name: 'closeout',
    tagline: 'Settle, and finish.',
    brand: {
      ...LIT,
      name: 'closeout',
      shape: CLOSEOUT,
      charge: interlace(MARK_SHARE.closeout, TOTAL),
    },
  },
];

/**
 * The marks again, flat and unlit, for the docs site's 3D stage.
 *
 * A separate projection rather than the published asset because the two want
 * opposite things: the asset carries its own light (sheen, bevel, outline) and
 * the stage supplies light of its own, so shipping the lit version into a
 * renderer would light it twice. Derived here rather than hand-copied, so it
 * cannot drift from the mark it is supposed to be.
 *
 * `markings` are omitted where they are drawn oversized and rely on the clip:
 * a renderer has no clip, and an extruded overhang is worse than a plain body.
 */
function unlit(brand: BurgeeBrand, keepMarkings: boolean): string {
  const shape = brand.shape ?? burgeeFlagPath();
  const markings = keepMarkings ? (brand.markings ?? '') : '';
  const charge = brand.charge ?? chargeGroup(brand.mark);
  return (
    `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" width="100" height="100">` +
    `<path d="${shape}" fill="${INK}" fill-rule="evenodd"/>${markings}` +
    `${brand.charge === undefined ? charge : placeCharge(charge)}</svg>`
  );
}

/** Whose markings survive the trip: the ones drawn inside their own outline. */
const CLIP_FREE: Record<string, boolean> = { roundel: true, flagstaff: true, caique: false };

/** Every surface, and the file that consumes it. */
const surfaces: ReadonlyArray<{ path: string; svg: string }> = [
  { path: 'brand-assets/burgee-flag.svg', svg: burgee.flag(MASTER) },
  // The moving one. Web only — a favicon that shimmers is a favicon that nags.
  { path: 'brand-assets/burgee-flag-alive.svg', svg: burgee.alive(MASTER) },
  { path: 'apps/docs/public/brand/burgee.svg', svg: unlit(BURGEE_DECLARATION, false) },
  { path: 'brand-assets/burgee-lockup.svg', svg: burgee.lockup({ theme: 'dark' }) },
  { path: 'brand-assets/burgee-lockup-light.svg', svg: burgee.lockup({ theme: 'light' }) },
  { path: 'brand-assets/burgee-og.svg', svg: burgee.og({ subtitle: TAGLINE }) },
  { path: 'brand-assets/burgee-cover.svg', svg: burgee.cover({ subtitle: TAGLINE }) },
  // The favicon master the docs site serves at /icon.svg.
  { path: 'apps/docs/src/app/icon.svg', svg: burgee.favicon() },
  // One flag and both lockups per sibling: the flag for a favicon or an avatar,
  // the lockups for the package README, which is read on both grounds.
  ...siblings.flatMap(({ name, tagline, brand }) => {
    const mark = defineBurgee(brand);
    return [
      { path: `brand-assets/${name}-flag.svg`, svg: mark.flag(MASTER) },
      { path: `brand-assets/${name}-flag-alive.svg`, svg: mark.alive(MASTER) },
      { path: `apps/docs/public/brand/${name}.svg`, svg: unlit(brand, CLIP_FREE[name] ?? false) },
      {
        path: `brand-assets/${name}-lockup.svg`,
        svg: mark.lockup({ theme: 'dark', subtitle: tagline }),
      },
      {
        path: `brand-assets/${name}-lockup-light.svg`,
        svg: mark.lockup({ theme: 'light', subtitle: tagline }),
      },
    ];
  }),
];

const MARK_COMPONENT = 'apps/docs/src/components/burgee-flag.tsx';

/**
 * The values the React component must carry. It writes them as JSX rather than
 * as one generated string, so the check is per value: colours, the swallowtail
 * path, the charge placement and the angle.
 */
const FLAG_DATA_URI = `data:image/svg+xml;base64,${Buffer.from(burgee.flag(MASTER)).toString('base64')}`;

/**
 * The sheen, read back out of what was just generated rather than restated here.
 * The component draws its own copy of the band, so the numbers it has to carry
 * are whatever `burgee/brand` emitted — not a third statement of them.
 */
const SHEEN_BAND =
  /skewX\((?<lean>-?[\d.]+)\)[^]*?(?<rect><rect x="-?[\d.]+" y="-?[\d.]+" width="[\d.]+" height="[\d.]+")/u.exec(
    burgee.flag(MASTER),
  )?.groups;

/** The bevel's two passes, read back out of the generated flag for the same reason. */
const BEVEL_PASSES = [...burgee.flag(MASTER).matchAll(/stroke-opacity="([\d.]+)"/gu)].map(
  (m) => m[1],
);

const COMPONENT_VALUES: ReadonlyArray<[string, string]> = [
  ['rock', ROCK_LIFT],
  ['juniper', JUNIPER_LIFT],
  ['ink', INK],
  ['outline', PAPER],
  ['flag path', burgeeFlagPath()],
  ['charge placement', chargeTransform()],
  ['charge angle', chargeRotation()],
  ['sheen', `stopOpacity="${SHEEN.toFixed(2)}"`],
  ['sheen lean', `skewX(${SHEEN_BAND?.lean ?? '?'})`],
  ['sheen band', SHEEN_BAND?.rect ?? '?'],
  ['bevel lit', `strokeOpacity="${BEVEL_PASSES[0] ?? '?'}"`],
  ['bevel shaded', `strokeOpacity="${BEVEL_PASSES[1] ?? '?'}"`],
  ['data URI', FLAG_DATA_URI],
];

function body(svg: string): string {
  return `${GENERATED}\n${svg}\n`;
}

function read(path: string): string | null {
  try {
    return readFileSync(join(repo, path), 'utf8');
  } catch {
    return null;
  }
}

/**
 * The component keeps its paths as literals so it stays a plain React component
 * with no build-time dependency on this script. That is a copy, so it is checked.
 */
function componentDrift(): string | null {
  const source = read(MARK_COMPONENT);
  if (source === null) return `${MARK_COMPONENT} is missing`;
  for (const [what, value] of COMPONENT_VALUES) {
    if (!source.includes(value)) return `${MARK_COMPONENT}: ${what} is not '${value}'`;
  }
  return null;
}

const check = process.argv.includes('--check');
const drifted: string[] = [];

for (const surface of surfaces) {
  const want = body(surface.svg);
  if (check) {
    if (read(surface.path) !== want) drifted.push(surface.path);
    continue;
  }
  const target = join(repo, surface.path);
  mkdirSync(dirname(target), { recursive: true });
  writeFileSync(target, want);
}

const componentProblem = componentDrift();
if (componentProblem !== null) drifted.push(componentProblem);

if (check && drifted.length > 0) {
  console.error('brand assets have drifted from the declaration:');
  for (const d of drifted) console.error(`  ${d}`);
  console.error('\nrun `npm run brand` to regenerate.');
  process.exitCode = 1;
} else if (check) {
  console.log(`brand: ${surfaces.length} surfaces and the mark component match the declaration`);
} else {
  for (const surface of surfaces) console.log(`wrote ${relative('.', surface.path)}`);
  // satori cannot resolve `url(#gradient)`, so the OG route draws the flag as an
  // image rather than as SVG elements. Print the value it must carry.
  console.log(`\nBURGEE_FLAG_DATA_URI (paste into burgee-flag.tsx):\n${FLAG_DATA_URI}`);
}

// Writing cannot fix the component: it keeps its own literals, so a mismatch
// after a write is a hand edit someone still owes.
if (!check && componentProblem !== null) {
  console.error(`\n${componentProblem}`);
  console.error('the component carries its own copy — update it by hand, then re-run --check.');
  process.exitCode = 1;
}

