/**
 * Lock — `compat:page --check` gates on the measurement, not on the clock.
 *
 * The page carries the date of the run that produced it, and the Ratchet job runs the oracle
 * *fresh* before comparing. So a byte-equality check held only until the next UTC midnight:
 * the three runs on 2026-09-09 were green and the first run at 01:39 on 2026-09-10 was red,
 * with every one of its twenty-four measured cells identical to the committed page. Nothing
 * about compatibility had changed; the date had.
 *
 * That is the worst shape for a gate. A red tick that means "it is tomorrow" teaches everyone
 * who sees it to re-run the job, and the next time the page really has gone stale it reads
 * exactly the same.
 */
import { describe, expect, it } from 'vitest';

import { drift } from './compat-page.js';

const page = (date: string, commander: string): string =>
  [
    '---',
    'title: Compatibility',
    '---',
    '',
    `Generated by \`npm run compat:page\` from the oracle's last run on ${date}.`,
    'Do not edit by hand.',
    '',
    '| Host | Front-end | burgee | rate |',
    '| :--- | :--- | ---: | ---: |',
    `| **commander** | \`burgee/commander\` | ${commander} | 100.0% |`,
    '',
  ].join('\n');

describe('drift', () => {
  it('is not drift when only the run date moved', () => {
    expect(drift(page('2026-09-09', '1360 / 1360'), page('2026-09-10', '1360 / 1360'))).toBeUndefined();
  });

  it('is drift when a measured number moved, and names the line and both values', () => {
    const found = drift(page('2026-09-09', '1360 / 1360'), page('2026-09-09', '1359 / 1360'));
    expect(found).toBeDefined();
    expect(found?.line).toBe(10);
    expect(found?.committed).toContain('1360 / 1360');
    expect(found?.generated).toContain('1359 / 1360');
  });

  it('is drift when a number moved AND the date moved — the date is ignored, not the row', () => {
    expect(drift(page('2026-09-09', '1360 / 1360'), page('2026-09-10', '1359 / 1360'))).toBeDefined();
  });

  it('normalises only the generated-on sentence, not every date on the page', () => {
    const withOtherDate = (d: string) => `${page('2026-09-09', '1360 / 1360')}\nvendored at 17.7.2 on ${d}.\n`;
    expect(drift(withOtherDate('2026-01-01'), withOtherDate('2026-02-02'))).toBeDefined();
  });

  it('reports a page that stops early rather than walking off the end', () => {
    const full = page('2026-09-09', '1360 / 1360');
    expect(drift(full.split('\n').slice(0, 5).join('\n'), full)).toBeDefined();
  });
});
