/**
 * Writes apps/docs/content/docs/compatibility.mdx from the oracle's last results. Generated,
 * never hand-edited, so the published number is the measured number (B7, C2).
 */
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { HOSTS } from 'compat-oracle/hosts';

const root = resolve(fileURLToPath(new URL('..', import.meta.url)));
const oracle = join(root, 'packages', 'compat-oracle');
const OUT = join(root, 'apps', 'docs', 'content', 'docs', 'compatibility.mdx');
const PERCENT = 100;
/** Length of an ISO date, `YYYY-MM-DD`. */
const ISO_DATE = 10;

interface Grade {
  host: string;
  target: string;
  passed: number;
  reference: number;
  tests: number;
  rate: number;
  note?: string;
  error?: string;
}
interface Results {
  measured: string;
  grades: Grade[];
}

function read(file: string): Results | undefined {
  const p = join(oracle, file);
  return existsSync(p) ? (JSON.parse(readFileSync(p, 'utf8')) as Results) : undefined;
}

const burgee = read('results.json');
const control = read('results.control.json');
const pct = (g: Grade | undefined): string => (g === undefined ? '—' : `${(g.rate * PERCENT).toFixed(1)}%`);
const cell = (g: Grade | undefined): string => {
  if (g === undefined) return '—';
  if (g.note !== undefined) return `0 / ${g.reference} (${g.note})`;
  return `${g.passed} / ${g.reference > 0 ? g.reference : g.tests}`;
};

const rows = HOSTS.filter((h) => h.status === 'active').map((h) => {
  const b = burgee?.grades.find((g) => g.host === h.name);
  const c = control?.grades.find((g) => g.host === h.name);
  return `| **${h.name}** | \`${h.target}\` | ${cell(b)} | ${pct(b)} | ${cell(c)} | ${pct(c)} |`;
});
const others = HOSTS.filter((h) => h.status !== 'active').map((h) => `| ${h.name} | ${h.status} | ${h.note ?? ''} |`);

writeFileSync(
  OUT,
  `---
title: Compatibility
description: Each host's own test suite, run against burgee in CI. A published pass rate that only goes up — never the word "compatible".
---

Generated by \`npm run compat:page\` from the oracle's last run${burgee === undefined ? '' : ` on ${burgee.measured.slice(0, ISO_DATE)}`}.
Do not edit by hand.

Each row is the **host's own test suite** — vendored, unmodified apart from the import
specifier — pointed at burgee's front-end through a generated shim. The *control* column is
the same suite pointed at the real host: it proves the gate works before it grades anything
of ours, and it is the reference total every rate is measured against. A file that fails to
import registers as one test instead of its twenty, so measuring against registered tests
would flatter a partial implementation; measuring against the control's total does not.

| Host | Front-end | burgee | rate | control | rate |
| :--- | :--- | ---: | ---: | ---: | ---: |
${rows.join('\n')}

A front-end does not reach 1.0 until its rate is **100%** (C7). Below that it ships pre-1.0
and is never described as compatible. The rate ratchets: a pull request that lowers it fails
CI unless it edits the baseline with a written reason (C5).

## Other hosts

| Host | Status | Why |
| :--- | :--- | :--- |
${others.join('\n')}

## Reproduce

\`\`\`bash
npm run compat -- --vendor --control   # vendor both suites, grade the real hosts
npm run compat                          # grade burgee
\`\`\`
`,
);
process.stdout.write(`wrote ${OUT}\n`);
