/**
 * What the community is already asking our competitors for.
 *
 * `foundation-baseline.ts` measures what an incumbent *costs*. This measures what it is
 * *missing*, from the only source that is not our own opinion: the issues its own users
 * opened and its own maintainer left open.
 *
 * The output decides two things that are otherwise argued:
 *
 *   1. **Whether a layer has a gap at all.** A layer whose incumbents carry no open issues
 *      has no community pain to relieve, and "we are better" there can only mean weight or
 *      consolidation — never "we fixed what they would not".
 *   2. **Whether a layer needs an extension point.** Requests of the form *"support X too"*
 *      are one shape: a caller wanting a format, loader or backend the author has to add by
 *      hand. When they dominate a layer, the answer is a published extension surface
 *      (PRINCIPLES rule 7), and this list is its seed corpus — not evangelism.
 *
 * Run: `npx tsx scripts/competitor-issues.ts` (needs `gh` authenticated; writes markdown).
 */
import { execFileSync } from 'node:child_process';

/** Repos behind each layer's incumbents, from each intent's own "Replaces" table. */
const LAYERS: Record<string, string[]> = {
  linegauge: [
    'sindresorhus/string-width',
    'chalk/wrap-ansi',
    'chalk/slice-ansi',
    'chalk/strip-ansi',
    'sindresorhus/cli-truncate',
    'sindresorhus/widest-line',
    'timoxley/wcwidth',
  ],
  closeout: ['tapjs/signal-exit', 'sindresorhus/exit-hook', 'sindresorhus/cli-cursor', 'sindresorhus/onetime'],
  seniority: ['cosmiconfig/cosmiconfig', 'antonk52/lilconfig', 'motdotla/dotenv', 'unjs/c12', 'dominictarr/rc'],
  bellpull: ['sindresorhus/execa', 'tinylibs/tinyexec', 'npm/node-which', 'sindresorhus/npm-run-path'],
};

/**
 * A request for something the author must add by hand — a format, a loader, a backend.
 * These are the ones an extension point answers wholesale instead of one at a time.
 */
const EXTENSION_SHAPED = /\b(support|add)\b.{0,40}\b(format|loader|parser|toml|yaml|json5|\.ts|rc|vite|plugin|adapter|backend)\b/i;

interface Issue {
  title: string;
  comments: number;
  url: string;
}

function issues(repo: string): Issue[] | undefined {
  try {
    const out = execFileSync(
      'gh',
      ['api', `repos/${repo}/issues?state=open&per_page=100`, '--jq', '[.[] | select(.pull_request == null) | {title, comments, url: .html_url}]'],
      { encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'] },
    );
    return JSON.parse(out) as Issue[];
  } catch {
    return undefined;
  }
}

const rows: string[] = [];
for (const [layer, repos] of Object.entries(LAYERS)) {
  rows.push(`\n#### ${layer}\n`, '| incumbent | open issues | extension-shaped | most discussed |', '| :-- | --: | --: | :-- |');
  let total = 0;
  let ext = 0;
  const seeds: string[] = [];
  for (const repo of repos) {
    const list = issues(repo);
    if (list === undefined) {
      rows.push(`| \`${repo}\` | *unreachable* | | |`);
      continue;
    }
    const extension = list.filter((i) => EXTENSION_SHAPED.test(i.title));
    total += list.length;
    ext += extension.length;
    for (const i of extension) seeds.push(`- \`${repo}\` — [${i.title}](${i.url}) · ${i.comments} comments`);
    const top = [...list].sort((a, b) => b.comments - a.comments)[0];
    rows.push(`| \`${repo}\` | ${list.length} | ${extension.length} | ${top === undefined ? '—' : `${top.title} (${top.comments}c)`} |`);
  }
  rows.push(`| **layer** | **${total}** | **${ext}** | |`);
  if (seeds.length > 0) rows.push('', `**Extension-shaped requests in ${layer}** — the seed corpus for its plugin surface:`, '', ...seeds);
}

process.stdout.write(
  [
    `<!-- generated by scripts/competitor-issues.ts on ${new Date().toISOString().slice(0, 'YYYY-MM-DD'.length)}; do not hand-edit -->`,
    '',
    ...rows,
    '',
  ].join('\n'),
);
