/**
 * Writes apps/docs/content/docs/compatibility.mdx from the oracle's last results. Generated,
 * never hand-edited, so the published number is the measured number (B7, C2).
 */
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { HOSTS } from 'compat-oracle/hosts';

const root = resolve(fileURLToPath(new URL('..', import.meta.url)));
const oracle = join(root, 'packages', 'compat-oracle');
const OUT = join(root, 'apps', 'docs', 'content', 'docs', 'compatibility.mdx');
const PERCENT = 100;
/** Length of an ISO date, `YYYY-MM-DD`. */
const ISO_DATE = 10;

interface Grade {
  host: string;
  target: string;
  passed: number;
  reference: number;
  tests: number;
  rate: number;
  note?: string;
  error?: string;
  internals?: { files: number; tests: number; passed: number };
}
interface Results {
  measured: string;
  grades: Grade[];
}

function read(file: string): Results | undefined {
  const p = join(oracle, file);
  return existsSync(p) ? (JSON.parse(readFileSync(p, 'utf8')) as Results) : undefined;
}

const burgee = read('results.json');
const control = read('results.control.json');
const pct = (g: Grade | undefined): string => (g === undefined ? '—' : `${(g.rate * PERCENT).toFixed(1)}%`);
const cell = (g: Grade | undefined): string => {
  if (g === undefined) return '—';
  if (g.note !== undefined) return `0 / ${g.reference} (${g.note})`;
  return `${g.passed} / ${g.reference > 0 ? g.reference : g.tests}`;
};

const internals = (g: Grade | undefined): string => (g?.internals === undefined ? '—' : `${g.internals.passed} / ${g.internals.tests}`);
const rows = HOSTS.filter((h) => h.status === 'active').map((h) => {
  const b = burgee?.grades.find((g) => g.host === h.name);
  const c = control?.grades.find((g) => g.host === h.name);
  return `| **${h.name}** | \`${h.target}\` | ${cell(b)} | ${pct(b)} | ${cell(c)} | ${pct(c)} | ${internals(b)} | ${internals(c)} |`;
});
const others = HOSTS.filter((h) => h.status !== 'active').map((h) => `| ${h.name} | ${h.status} | ${h.note ?? ''} |`);

/**
 * Every excluded case, published by name. `compat-oracle/intent.md`: "the exclusion list is
 * explicit, named and justified in the repo — an exclusion that grows silently is how a
 * compat claim becomes a lie." Generated from `hosts.ts`, so it cannot drift from the gate.
 */
const excluded = HOSTS.filter((h) => (h.excludes ?? []).length > 0).flatMap((h) => (h.excludes ?? []).map((e) => `| **${h.name}** | \`${e.match.trim()}\` | ${e.why} |`));

const page = `---
title: Compatibility
description: Each host's own test suite, run against burgee in CI. A published pass rate that only goes up — never the word "compatible".
---

Generated by \`npm run compat:page\` from the oracle's last run${burgee === undefined ? '' : ` on ${burgee.measured.slice(0, ISO_DATE)}`}.
Do not edit by hand.

Each row is the **host's own test suite** — vendored, unmodified apart from the import
specifier — pointed at burgee's front-end through a generated shim. The *control* column is
the same suite pointed at the real host: it proves the gate works before it grades anything
of ours, and it is the reference total every rate is measured against. A file that fails to
import registers as one test instead of its twenty, so measuring against registered tests
would flatter a partial implementation; measuring against the control's total does not.

| Host | Front-end | burgee | rate | control | rate | internals (burgee) | internals (control) |
| :--- | :--- | ---: | ---: | ---: | ---: | ---: | ---: |
${rows.join('\n')}

**Every file of every suite is vendored and run**, and every case that leaves the gate is
named below. Files that import only the host's *internal* modules (its own file layout) are
graded on the informational *internals* columns and never enter the gate: passing them would
mean copying the host, not being compatible with it. A public-surface file that also touches
an internal module stays in the gate, with that import shimmed to our main entry.
${
  excluded.length === 0
    ? ''
    : `
### Cases excluded from the gate

A case that cannot fail for any implementation measures nothing, and counting it inflates the
rate. These are excluded by name — they still run, and they still appear in the raw TAP.

| Host | Cases | Why |
| :--- | :--- | :--- |
${excluded.join('\n')}
`
}
## Supported majors

Compatibility is claimed only where it is graded, and it is graded against the host's
**current major** — the suite is vendored at the tag of the latest npm release, so the
number above always names a release, never a branch.

| Host | Major graded | Release | Older majors |
| :-- | :-- | :-- | :-- |
| commander | **15** (current) | 15.0.0 | Programs written for 12–14 run unchanged wherever 15 kept their API; each earlier major's own suite is vendored at its last tag and graded before it is listed here (C1) |
| yargs | **18** (current) | 18.1.0 | Programs written for 17 run unchanged wherever 18 kept their API; 17's own suite is vendored at its last tag and graded before it is listed here (C1) |
| chalk | **6** (current) | 6.0.0 | Programs written for 5 run unchanged: 6 added underline styles and colours and made a numeric \`FORCE_COLOR\` an exact level; 5's own suite is vendored at its last tag and graded before it is listed here (C1) |
| ora | **9** (current) | 9.4.1 | Programs written for 8 run unchanged wherever 9 kept their API; 8's own suite is vendored at its last tag and graded before it is listed here (C1) |
| log-update | **8** (current) | 8.0.0 | Programs written for 7 run unchanged wherever 8 kept their API; 7's own suite is vendored at its last tag and graded before it is listed here (C1) |
| cli-table3 | **0.6** (current) | 0.6.5 | Its only major; 0.6's suite is what is graded here |

A new major of a host is a new line here, opened by the daily release watch the day it
ships; the previous major stays listed for as long as its suite is still graded.

A front-end does not reach 1.0 until its rate is **100%** (C7). Below that it ships pre-1.0
and is never described as compatible. The rate ratchets: a pull request that lowers it fails
CI unless it edits the baseline with a written reason (C5).

## Other hosts

| Host | Status | Why |
| :--- | :--- | :--- |
${others.join('\n')}

## Reproduce

\`\`\`bash
npm run compat -- --vendor --control   # vendor both suites, grade the real hosts
npm run compat                          # grade burgee
\`\`\`
`;

/**
 * `--check` for the same reason `bench:page` has one: this page is generated and it went
 * stale in silence. `flagstaff/cli-table3` was graded 29 / 29 and the published table went
 * on saying `flagstaff/table` 0 / 29 — the number was measured, merged, and never reached
 * the page, because nothing compared the two.
 *
 * It runs in the Ratchet job rather than on every check, because a full page needs both
 * halves: `results.json` from the target grade and `results.control.json` from the control,
 * and the control's numbers are the Linux ones (yargs scores 802 / 804 there and 804 / 804
 * elsewhere). One job that produces both is the only place the comparison means anything.
 */
if (!process.argv.includes('--check')) {
  writeFileSync(OUT, page);
  process.stdout.write(`wrote ${OUT}\n`);
} else if (!existsSync(OUT) || readFileSync(OUT, 'utf8') !== page) {
  process.stderr.write(`✖ ${OUT} is not what \`npm run compat:page\` produces from the oracle's results.\n  Run the oracle and \`npm run compat:page\`, and commit the result — the page says it is generated, and this is what makes that true.\n`);
  process.exitCode = 1;
} else {
  process.stdout.write(`✓ ${OUT} matches the measured results\n`);
}
