/**
 * Copyright (c) 2026 Ofri Peretz
 * Licensed under the MIT License. Use of this source code is governed by the
 * MIT license that can be found in the LICENSE file.
 */

/**
 * Lock — every published package README shares one header and one shape.
 *
 * On 2026-09-27 burgee and roundel opened with a tagline and five badges, flagstaff and caique
 * with a tagline and three or four, and bellpull, closeout, linegauge, paratext and seniority
 * with no tagline and no badge at all. No README carried a CI, coverage, Scorecard, size or
 * compatibility badge, and each section order was its own. READMEs written separately drift
 * separately, and npm shows every one of them as the package's front page.
 *
 * The badge rows and the family table are generated by `scripts/readme-benchmarks.ts` and held
 * byte for byte by `readme-lock.test.ts`. What this adds is the standard itself, so that it
 * cannot be generated away or skipped for one package:
 *
 *   - **the header**: the lockup, a one-line tagline, the badge row with every kind in one
 *     order — each a link with alt text — a compatibility row when the package is graded, then
 *     the Docs line;
 *   - **the sections**: Install (npm, pnpm, yarn, bun), Quick start, Migrating (with a diff),
 *     Compatibility, Benchmarks, For agents (with the docs host's llms.txt), API, Where it
 *     sits, The family (every package in `FAMILY`), Contributing and Licence, in that order —
 *     other sections may sit between them;
 *   - **a reserved package** (description opens "Reserved"; `controlroom@0.0.1` on 2026-09-28)
 *     keeps the same shape and says so: a `status: reserved` badge in the coverage slot, since
 *     a placeholder's coverage would read as a claim; no compatibility row, since nothing is
 *     graded; and a Docs line that need not name a migration guide that does not exist yet;
 *   - **an ungraded package** has no compatibility row, and its Compatibility section says
 *     "not graded" rather than leaving the reader to infer it from an absence;
 *   - **links that work on npm**: npm renders the README too, and a relative link there
 *     resolves against npmjs.com.
 */
import { existsSync, readdirSync, readFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { describe, expect, it } from 'vitest';

import { FAMILY, grades, headerBlocks, reserved } from './readme-benchmarks.js';

const ROOT = resolve(fileURLToPath(new URL('..', import.meta.url)));
const PACKAGES = join(ROOT, 'packages');

const manifest = (name: string): { private?: boolean } => JSON.parse(readFileSync(join(PACKAGES, name, 'package.json'), 'utf8')) as { private?: boolean };

/** Published packages with a README — `compat-oracle` is internal and ships to nobody. */
const published = (): string[] =>
  readdirSync(PACKAGES).filter((name) => existsSync(join(PACKAGES, name, 'package.json')) && manifest(name).private !== true && existsSync(join(PACKAGES, name, 'README.md')));

/**
 * The badge kinds, in the one order every README carries them, each recognised by its image URL.
 * `{pkg}` stands for the package the README is about: a badge for a sibling is the wrong badge.
 */
export const BADGES: readonly (readonly [kind: string, src: string])[] = [
  ['npm version', String.raw`^https://img\.shields\.io/npm/v/{pkg}\?`],
  ['downloads', String.raw`^https://img\.shields\.io/npm/dm/{pkg}\?`],
  ['Quality Gate', String.raw`^https://img\.shields\.io/github/actions/workflow/status/ofri-peretz/burgee/quality\.yml\?branch=main`],
  ['coverage', String.raw`^https://img\.shields\.io/codecov/c/github/ofri-peretz/burgee/main\?component={pkg}&`],
  ['OpenSSF Scorecard', String.raw`^https://img\.shields\.io/ossf-scorecard/github\.com/ofri-peretz/burgee\?`],
  ['size', String.raw`^https://img\.shields\.io/npm/unpacked-size/{pkg}\?`],
  ['dependencies', String.raw`^https://img\.shields\.io/badge/dependencies-`],
  ['types', String.raw`^https://img\.shields\.io/badge/types-included-`],
  ['Node.js', String.raw`^https://img\.shields\.io/badge/Node\.js-`],
  ['License', String.raw`^https://img\.shields\.io/badge/License-`],
  ['status', String.raw`^https://img\.shields\.io/badge/status-reserved-`],
  ['provenance', String.raw`^https://img\.shields\.io/badge/dynamic/json\?url=https%3A%2F%2Fregistry\.npmjs\.org%2F{pkg}%2Flatest&query=%24\.dist\.attestations\.provenance`],
];

/** The sections every README carries, in this order; its own sections may sit between them. */
export const SECTIONS = ['Install', 'Quick start', 'Migrating', 'Compatibility', 'Benchmarks', 'For agents', 'API', 'Where it sits', 'The family', 'Contributing', 'Licence'] as const;

const FAMILY_SIZE = FAMILY.length;
const BADGE = /^ {2}<a href="(https:\/\/[^"]+)"><img src="([^"]+)" alt="([^"]*)" \/><\/a>$/u;
const RELATIVE = /\]\((\.{0,2}\/[^)\s]*)\)|(?:href|src|srcset)="(\.{0,2}\/[^"]*)"/gu;
/** The shortest alt text that still says something: `License: MIT`. */
const MIN_ALT = 12;

interface Badge {
  href: string;
  src: string;
  alt: string;
}

/** Each `<a href><img src alt></a>` in a badge row; a bare `<img>` comes back with no `href`. */
const badgesIn = (block: string): Badge[] =>
  block
    .split('\n')
    .filter((line) => line.includes('<img'))
    .map((line) => {
      const m = BADGE.exec(line);
      return { href: m?.[1] ?? '', src: m?.[2] ?? /src="([^"]+)"/u.exec(line)?.[1] ?? '', alt: m?.[3] ?? '' };
    });

/** Which standard badge an image URL is, for this package. */
const kindOf = (src: string, pkg: string): string => BADGES.find(([, re]) => new RegExp(re.replaceAll('{pkg}', pkg), 'u').test(src))?.[0] ?? `unrecognised badge ${src}`;

/** The body of one `## ` section, or `''` when the README has none. */
const sectionBody = (readme: string, heading: string): string => {
  const at = readme.indexOf(`\n## ${heading}\n`);
  if (at === -1) return '';
  const next = readme.indexOf('\n## ', at + 1);
  return readme.slice(at, next === -1 ? undefined : next);
};

/** The lockup, the tagline and the Docs line: the three header blocks written by hand. */
function headerProblems(pkg: string, blocks: readonly string[], graded: boolean): string[] {
  const out: string[] = [];
  const expected = graded ? 5 : 4;
  if (blocks.length !== expected) out.push(`${pkg}: the header has ${String(blocks.length)} centred blocks, not ${String(expected)} (lockup, tagline, badges${graded ? ', compatibility' : ''}, Docs)`);
  const [lockup = '', tagline = ''] = blocks;
  if (!lockup.includes('<picture>') || !lockup.includes(`https://raw.githubusercontent.com/ofri-peretz/burgee/main/brand-assets/${pkg}-lockup`)) out.push(`${pkg}: the header does not open with its lockup, by absolute URL`);
  if (/<(?:a|img|picture)\b/u.test(tagline) || tagline.replaceAll(/<\/?p[^>]*>/gu, '').trim() === '') out.push(`${pkg}: the second header block is not a one-line tagline`);
  const docs = blocks.at(-1) ?? '';
  if (!docs.includes('Docs:')) out.push(`${pkg}: the header does not close with the Docs line`);
  if (!reserved(pkg) && !docs.includes('Migrating from:')) out.push(`${pkg}: the Docs line names no migration guide — only a reserved package may omit "Migrating from:"`);
  return out;
}

/** The badge row in the standard order, a compatibility badge per graded suite, each a link with alt text. */
function badgeProblems(pkg: string, blocks: readonly string[], graded: number): string[] {
  const out: string[] = [];
  const row = badgesIn(blocks[2] ?? '');
  const kinds = row.map(({ src }) => kindOf(src, pkg));
  // One order for everyone. A reserved package swaps coverage for its status, in the same slot.
  const order = BADGES.map(([kind]) => kind)
    .filter((kind) => kind !== 'status')
    .map((kind) => (kind === 'coverage' && reserved(pkg) ? 'status' : kind));
  if (kinds.join('|') !== order.join('|')) out.push(`${pkg}: the badge row reads [${kinds.join(', ')}], not [${order.join(', ')}]`);
  const suites = graded > 0 ? badgesIn(blocks[3] ?? '') : [];
  if (suites.length !== graded) out.push(`${pkg}: ${String(graded)} graded suites and ${String(suites.length)} compatibility badges`);
  for (const b of [...row, ...suites]) {
    if (b.href === '') out.push(`${pkg}: a badge (${b.src}) is not wrapped in an absolute link`);
    if (b.alt.trim().length < MIN_ALT) out.push(`${pkg}: a badge (${b.src}) has no descriptive alt text`);
  }
  return out;
}

/** The standard sections, in order, and the one fact each of them owes. */
function sectionProblems(pkg: string, readme: string): string[] {
  const out: string[] = [];
  let last = -1;
  for (const heading of SECTIONS) {
    const at = readme.indexOf(`\n## ${heading}\n`);
    if (at === -1) out.push(`${pkg}: no \`## ${heading}\` section`);
    else if (at < last) out.push(`${pkg}: \`## ${heading}\` is out of order — the standard is ${SECTIONS.join(' → ')}`);
    else last = at;
  }
  const install = sectionBody(readme, 'Install');
  const missing = [`npm install ${pkg}`, `pnpm add ${pkg}`, `yarn add ${pkg}`, `bun add ${pkg}`].filter((line) => !install.includes(line));
  out.push(...missing.map((line) => `${pkg}: Install has no \`${line}\``));
  if (!sectionBody(readme, 'Migrating').includes('```diff\n')) out.push(`${pkg}: Migrating shows no before/after diff`);
  if (grades(pkg).length === 0 && !/\bnot graded\b/iu.test(sectionBody(readme, 'Compatibility'))) out.push(`${pkg}: nothing is graded, and Compatibility does not say "not graded"`);
  if (!sectionBody(readme, 'For agents').includes('.interlace.tools/llms.txt')) out.push(`${pkg}: For agents does not link the docs host's llms.txt`);
  const rows = sectionBody(readme, 'The family')
    .split('\n')
    .filter((line) => /^\| (?:\[|\*\*)[a-z]+/u.test(line));
  if (rows.length !== FAMILY_SIZE) out.push(`${pkg}: the family table has ${String(rows.length)} rows, not ${String(FAMILY_SIZE)}`);
  if (!sectionBody(readme, 'Contributing').includes('/SECURITY.md')) out.push(`${pkg}: Contributing does not link SECURITY.md`);
  return out;
}

/** Everything wrong with one README against the standard, or nothing. */
export function problems(pkg: string, readme: string): string[] {
  const { blocks } = headerBlocks(readme);
  const graded = grades(pkg).length;
  const relative = [...readme.matchAll(RELATIVE)].map((m) => m[1] ?? m[2] ?? '');
  return [
    ...headerProblems(pkg, blocks, graded > 0),
    ...badgeProblems(pkg, blocks, graded),
    ...sectionProblems(pkg, readme),
    ...(relative.length > 0 ? [`${pkg}: relative links resolve against npmjs.com on npm — ${relative.join(', ')}`] : []),
  ];
}

const read = (pkg: string): string => readFileSync(join(PACKAGES, pkg, 'README.md'), 'utf8');

describe('every published README has the family header and shape', () => {
  const names = published();

  it('has the whole family to check', () => {
    expect(names).toHaveLength(FAMILY_SIZE);
  });

  it.each(names)('%s', (pkg) => {
    expect(problems(pkg, read(pkg))).toEqual([]);
  });
});

describe('the lock can fail', () => {
  const pkg = 'roundel';

  it('fails a badge row in another order', () => {
    const text = read(pkg);
    const lines = text.split('\n');
    const first = lines.findIndex((l) => l.includes('img.shields.io/npm/v/'));
    [lines[first], lines[first + 1]] = [lines[first + 1] as string, lines[first] as string];
    expect(lines.join('\n')).not.toBe(text);
    expect(problems(pkg, lines.join('\n')).join('\n')).toMatch(/the badge row reads \[downloads, npm version/u);
  });

  it('fails a README with no tagline', () => {
    const { blocks } = headerBlocks(read(pkg));
    const text = read(pkg).replace(`${blocks[1] ?? ''}\n\n`, '');
    expect(text).not.toBe(read(pkg));
    expect(problems(pkg, text).join('\n')).toMatch(/not a one-line tagline/u);
  });

  it('fails a badge without alt text, and one that is not a link', () => {
    const text = read(pkg).replace(/alt="roundel downloads per month on npm"/u, 'alt=""').replace(/<a href="[^"]+"><img src="(https:\/\/img\.shields\.io\/badge\/types[^"]+)" alt="([^"]+)" \/><\/a>/u, '<img src="$1" alt="$2" />');
    expect(problems(pkg, text).join('\n')).toMatch(/no descriptive alt text[\s\S]*not wrapped in an absolute link|not wrapped in an absolute link[\s\S]*no descriptive alt text/u);
  });

  it('fails a section out of order, a missing install line and a relative link', () => {
    const text = read(pkg).replace('\n## API\n', '\n## Moved\n').replace('\n## Install\n', '\n## API\n\n## Install\n').replace('bun add roundel', 'bun i roundel').replace('](https://roundel.interlace.tools/docs)', '](./docs)');
    const found = problems(pkg, text).join('\n');
    expect(found).toMatch(/`## API` is out of order/u);
    expect(found).toMatch(/Install has no `bun add roundel`/u);
    expect(found).toMatch(/relative links resolve against npmjs\.com on npm — \.\/docs/u);
  });

  it('lets only a reserved package trade coverage for its status, or omit the migration guide', () => {
    const status = '<a href="https://github.com/ofri-peretz/burgee/tree/main/.sdlc/intents/roundel"><img src="https://img.shields.io/badge/status-reserved-a84c17?style=flat-square" alt="Status: reserved, not usable yet" /></a>';
    const text = read(pkg)
      .replace(/^ {2}<a href="https:\/\/app\.codecov\.io[^\n]*$/mu, `  ${status}`)
      .replace(/<br \/>\n\s*Migrating from:[^\n]*/u, '');
    expect(text).not.toBe(read(pkg));
    const found = problems(pkg, text).join('\n');
    expect(found).toMatch(/the badge row reads \[npm version, downloads, Quality Gate, status,/u);
    expect(found).toMatch(/only a reserved package may omit "Migrating from:"/u);
    expect(problems('controlroom', read('controlroom')), 'the reserved package itself passes').toEqual([]);
  });

  // controlroom was the ungraded package until its two rows landed (D-20261005-controlroom-ink-suite),
  // and every package is graded now — so a name no host targets stands in for the next one, read
  // through the section check alone, because the header checks read a manifest it does not have.
  it('fails an ungraded package whose Compatibility section does not say so', () => {
    const said = read('controlroom').replace(/## Compatibility\n\n[\s\S]*?\n## /u, '## Compatibility\n\nNot graded yet.\n\n## ');
    expect(said).not.toBe(read('controlroom'));
    expect(sectionProblems('ungraded-fixture', said).join('\n')).not.toMatch(/does not say "not graded"/u);
    expect(sectionProblems('ungraded-fixture', said.replace('Not graded yet.', 'Coming soon.')).join('\n')).toMatch(/does not say "not graded"/u);
  });
});
