/**
 * Copyright (c) 2026 Ofri Peretz
 * Licensed under the MIT License. Use of this source code is governed by the
 * MIT license that can be found in the LICENSE file.
 */

/**
 * roundel R11 — the theme gallery, generated from scheme files, none of it hand-written.
 *
 * Every Base16 scheme (`.yaml`, `.yml`, `.json`) and every iTerm2 preset (`.itermcolors`) in
 * `packages/roundel/src/__fixtures__/` is run through `roundel/import` — the same functions a
 * user calls — and becomes one row: the colour each token takes, its ratio on the scheme's own
 * ground, and whether roundel flies it. A refused scheme is listed with the slot that refused
 * it, because a gallery that showed only the survivors would hide the check it exists to show.
 * Adding a theme to the gallery is adding a file; the row is derived.
 *
 * A file the importers refuse for its *format* stops the script: a broken gallery file is a
 * defect in the gallery, not a row.
 *
 *   npx tsx scripts/roundel-gallery.ts          # write
 *   npx tsx scripts/roundel-gallery.ts --check  # exit 1 on drift
 */
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, extname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

// eslint-disable-next-line import-next/no-relative-packages -- by path: the gallery is generated from the source the tests pin, not from a built copy that may be stale
import { contrast, floors } from '../packages/roundel/src/contrast.js';
// eslint-disable-next-line import-next/no-relative-packages -- by path, for the same reason
import { BASE16_SLOTS, fromBase16, fromITerm, ImportError, type ImportedToken, ITERM_SLOTS } from '../packages/roundel/src/import.js';
// eslint-disable-next-line import-next/no-relative-packages -- by path, for the same reason
import { audit, type Theme } from '../packages/roundel/src/theme.js';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
export const SCHEMES = join(ROOT, 'packages/roundel/src/__fixtures__');
export const PAGE = join(ROOT, 'apps/docs-roundel/content/docs/guides/theme-gallery.md');

const BASE16 = new Set(['.yaml', '.yml', '.json']);
const ITERM = '.itermcolors';
const COLOURED: readonly ImportedToken[] = ['error', 'warn', 'ok', 'flag', 'value'];

interface Row {
  file: string;
  format: 'Base16' | 'iTerm2';
  theme: Theme;
  refused: boolean;
}

function read(dir: string, file: string): Row {
  const ext = extname(file);
  const text = readFileSync(join(dir, file), 'utf8');
  const format = ext === ITERM ? 'iTerm2' : 'Base16';
  if (ext !== ITERM && !BASE16.has(ext)) throw new Error(`${file}: not a scheme the gallery reads (${[...BASE16, ITERM].join(', ')})`);
  try {
    return { file, format, theme: format === 'iTerm2' ? fromITerm(text) : fromBase16(text), refused: false };
  } catch (error) {
    if (error instanceof ImportError && error.code === 'E_IMPORT_CONTRAST' && error.theme !== undefined) return { file, format, theme: error.theme, refused: true };
    throw new Error(`${file}: ${error instanceof Error ? error.message : String(error)}`, { cause: error });
  }
}

const cell = (theme: Theme, token: ImportedToken): string => {
  const hex = theme[token] as string;
  return `\`${hex}\` ${contrast(hex, theme.ground as string).toFixed(2)}:1`;
};

function verdict(row: Row): string {
  if (!row.refused) return 'flies';
  const slots = row.format === 'iTerm2' ? ITERM_SLOTS : BASE16_SLOTS;
  const failing = [...new Set(audit(row.theme).filter((f) => !f.passes).map((f) => f.token as ImportedToken))];
  return `refused — ${failing.map((t) => `${t} (${slots[t]})`).join(', ')} below ${String(floors().TEXT)}:1`;
}

/** The page, from whatever scheme files are in `dir`. */
export function render(dir: string = SCHEMES): string {
  const rows = readdirSync(dir)
    .filter((f) => !f.startsWith('.'))
    .sort((a, b) => a.localeCompare(b))
    .map((f) => read(dir, f));
  const table = rows.map((r) => `| \`${r.file}\` | ${r.format} | ${verdict(r)} | \`${r.theme.ground as string}\` | ${COLOURED.map((t) => cell(r.theme, t)).join(' | ')} |`);
  return [
    '---',
    'title: Theme gallery',
    'description: "Base16 schemes and iTerm2 presets read by roundel/import: the colour each token takes, its contrast on the scheme\'s own background, and whether roundel flies it."',
    '---',
    '',
    '<!-- Generated by scripts/roundel-gallery.ts from packages/roundel/src/__fixtures__. Do not edit; run `npx tsx scripts/roundel-gallery.ts`. -->',
    '',
    'Every row is a scheme file read by `roundel/import` — `fromBase16` or `fromITerm`, the',
    'functions a program calls — and nothing in the table is typed by hand. Each colour is shown',
    "with its WCAG ratio on the scheme's own background; a scheme `fly()` would refuse is listed",
    'as refused, with the slot that refused it, rather than left out.',
    '',
    'The gallery is the scheme files in',
    '[`packages/roundel/src/__fixtures__/`](https://github.com/ofri-peretz/burgee/tree/main/packages/roundel/src/__fixtures__),',
    'which are also what `import.test.ts` pins the importers against. A theme joins it by adding',
    'its file; the row is derived.',
    '',
    '| Scheme | Format | roundel | ground | error | warn | ok | flag | value |',
    '| :-- | :-- | :-- | :-- | :-- | :-- | :-- | :-- | :-- |',
    ...table,
    '',
  ].join('\n');
}

if (process.argv[1]?.endsWith('roundel-gallery.ts') === true) {
  const page = render();
  if (!process.argv.slice(2).includes('--check')) writeFileSync(PAGE, page);
  else if (readFileSync(PAGE, 'utf8') === page) process.stdout.write('✓ the theme gallery matches its scheme files\n');
  else {
    process.stderr.write('✖ apps/docs-roundel/content/docs/guides/theme-gallery.md is stale. Run `npx tsx scripts/roundel-gallery.ts`.\n');
    process.exitCode = 1;
  }
}
